Repository easyscience/EasyDiffractionLib, pull requests merged in 2024-10, with the labels that each got.

#123 Fix bug in Simulation.ipynb
  examples/Simulation.ipynb
Labels: documentation

#139 Bump cryspy from beta to 0.7.7
  .github/workflows/test-ipynb.yml
  .github/workflows/verify-pr-labels.yml
  pyproject.toml
Labels: dependencies

#140 Bump easycrystallography from adp_cif_naming to develop
  .github/workflows/test-ipynb.yml
  pyproject.toml
Labels: chore
