Repository easyscience/EasyDiffractionLib, pull requests merged in 2024-11, with the labels that each got.

#144 Hotfix 0.1.4
  easydiffraction/Job.py
  pyproject.toml
Labels: bug, documentation

#146 make x-rays work with cryspy
  easydiffraction/Job.py
  examples_old/Simulation_xray.ipynb
Labels: enhancement

#147 Add more Jupyter notebook examples, etc.
  .github/workflows/release-drafter.yml
  .github/workflows/test-ipynb.yml
  .github/workflows/test-package.yaml
  easydiffraction/Job.py
  easydiffraction/Profiles/P1D.py
  easydiffraction/__init__.py
  easydiffraction/io/download.py
  examples/Change-minimizer.ipynb
  examples/Define-experiment.ipynb
  examples/Define-model.ipynb
  examples/Fitting-emcee_pd-neut-cwl_LBCO-HRPT.ipynb
  examples/Fitting_pd-neut-cwl_LBCO-HRPT.ipynb
  examples/Fitting_pd-neut-tof_NCAF-WISH.ipynb
  examples/Fitting_pd-neut-tof_Si-SEPD.ipynb
  examples/Simulation_pd-xray_NaCl.ipynb
  examples/data/d1a.cif
  examples/data/lbco_adp.cif
  examples_old/advanced/refinement_bumps_dream.ipynb
  examples_old/advanced/refinement_emcee.ipynb
  pyproject.toml
Labels: enhancement

#149 Fix release drafter workflow
  .github/workflows/release-drafter.yml
Labels: bug

#150 Fix 'Change-minimizer' Jupyter Notebook
  examples/Change-minimizer.ipynb
  pyproject.toml
Labels: bug

#151 Hotfix 0.1.7
  easydiffraction/io/cryspy_parser.py
  pyproject.toml
Labels: bug

#154 Fix parameter links to online documentation
  easydiffraction/Profiles/P1D.py
  easydiffraction/io/cryspy_parser.py
  pyproject.toml
Labels: bug
