Repository easyscience/EasyDiffractionLib, pull requests merged in 2025-01, with the labels that each got.

#164 Datastore fix dev
  src/easydiffraction/io/cif.py
  src/easydiffraction/job/experiment/backgrounds/background.py
  src/easydiffraction/job/experiment/experiment.py
  src/easydiffraction/job/job.py
  tests/integration_tests/fitting/test_fitting_pd-neut.py
  tests/unit_tests/job/experiment/test_experiment.py
  tests/unit_tests/job/test_job.py
Labels: refactor

#165 TOF fix
  examples/Fitting_pd-neut-tof_Si-SEPD.ipynb
  src/easydiffraction/calculators/cryspy/calculator.py
  src/easydiffraction/calculators/cryspy/wrapper.py
  src/easydiffraction/calculators/wrapper_base.py
  src/easydiffraction/calculators/wrapper_factory.py
  src/easydiffraction/job/job.py
  tests/functional_tests/fitting/test_fitting_pd-neut.py
Labels: bug

#166 Update logo links in README
  .github/workflows/ci-testing.yaml
  README.md
  tools/linting_and_formatting.sh
  tools/run_notebooks.sh
  tools/run_tests.sh
Labels: chore

#167 New release
  .github/workflows/ci-testing.yaml
  README.md
  examples/Fitting_pd-neut-tof_Si-SEPD.ipynb
  src/easydiffraction/calculators/cryspy/calculator.py
  src/easydiffraction/calculators/cryspy/wrapper.py
  src/easydiffraction/calculators/wrapper_base.py
  src/easydiffraction/calculators/wrapper_factory.py
  src/easydiffraction/io/cif.py
  src/easydiffraction/io/cif_reader.py
  src/easydiffraction/job/experiment/backgrounds/background.py
  src/easydiffraction/job/experiment/experiment.py
  src/easydiffraction/job/job.py
  src/easydiffraction/job/old_sample/old_sample.py
  tests/functional_tests/fitting/test_fitting_pd-neut.py
  tests/unit_tests/job/experiment/test_experiment.py
  tests/unit_tests/job/test_job.py
  tools/linting_and_formatting.sh
  tools/run_notebooks.sh
  tools/run_tests.sh
Labels: bug
